Repository opdev/opcap-ansible, pull requests merged in 2023-08, with the labels that each got.

#12 ADD fips-assessments for openshift serverless
  fips_assessment.yml
  install.yml
  vars.yml.example
Labels: size/S, tide/merge-method-rebase

#30 Adding a github action for ansible lint and fixing some linting issues
  .ansible-lint
  .github/workflows/ansible-lint.yml
  fips_assessment.yml
  install.yml
Labels: approved, lgtm

#33 Make the fips assessments dynamic
  audits.yml
  fips_assessment.yml
  install.yml
  operator_install.yml
Labels: approved, lgtm

#14 Add reporting for operator installs
  ansible.cfg
  audits.yml
  install.yml
Labels: size/M, approved, lgtm

#34 Add 'target_namespace' as a variable to call to fips assessments
  audits.yml
  install.yml
  vars.yml.example
Labels: approved, lgtm

#36 Fix the namespace variable
  install.yml
  templates/operator-group.yml.j2
  templates/subscription.yml.j2
Labels: approved, lgtm

#37 Report FIPS results into the stats
  fips_assessment.yml
  install.yml
Labels: approved, lgtm

#38 truncate more characters of package name
  install.yml
  operator_install.yml
Labels: approved, lgtm

#40 Add dependabot config
  .github/depdendabot.yml
Labels: approved

#41 Fix dependabot.yml spelling
  .github/dependabot.yml
Labels: approved
