Repository opdev/opcap-ansible, pull requests merged in 2023-07, with the labels that each got.

#3 ADD kubeconfig as an option for connection
  .gitignore
  README.md
Labels: size/XS

#7 Remove users no longer in org
  OWNERS
Labels: size/XS

#4 add execution environment file for ansible-builder
  README.md
  execution-environment.yml
  requirements.yml
Labels: size/M, approved, lgtm

#6 Rename and standardize on .yml
  .gitignore
  README.md
  audits.yml
  install.yml
  operator_install.yml
  vars.yml.example
Labels: size/S, approved, lgtm

#11 Update remaining task references from .yaml to .yml
  audits.yml
  operator_install.yml
Labels: size/XS, approved, lgtm

#10 Add GHA workflow to build ee image on PR merge
  .github/workflows/opcap-ansible-ee-build.yml
  requirements.txt
Labels: size/M, approved, lgtm

#13 Update requirements.txt and add venv instructions
  README.md
  requirements.txt
Labels: size/M, approved, lgtm

#15 ADD artifacts, log and .vscode to gitignore
  .gitignore
Labels: size/XS, approved, lgtm
